[tool.poetry]
name = "testing"
version = "0.1.0"
description = ""
authors = ["Carl Boettiger <cboettig@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandasai = "^2.2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
